# ***** REQUIRED INPUTS *****

# Path for input and output data
io:
    forcing_path: ''
    output_path: ''

# Absolute measurement heights/depths (in meters)
z:
    air_temp_m: 2.33     # m
    soil_temp_m: 1.0    # m
    wind_speed_m: 2.5   # m       

# Model parameters
params:
    elevation_m: 2000           # m
    roughness_length_m: 0.001   # m      


# ***** OPTIONAL INPUTS *****

# State variables for the initial snowpack
# Defaults to no snow (all variables zero)
# To specify a nonzero snowpack, replace null with the desired value for each variable
init:
    snow_depth_cm: null             # cm
    bulk_snow_density_kgm-3: null   # kg/m^3
    active_layer_temp_degC: null    # degC
    avg_snow_temp_degC: null        # degC
    h2o_sat_%: null                 # %

# Model defaults (values follow original pysnobal implementation)
# To override, replace null with the desired value
defaults:
    relative_heights: null                  # default value: False
    max_h2o_vol_frac: null                  # default value: 0.01 
    max_active_layer_thickness_m: null      # default value: 0.25 m
    normal_tstep_mass_thresh_kgm-2: null    # default value: 60 kg/m^2
    medium_tstep_mass_thresh_kgm-2: null    # default value: 10 kg/m^2
    small_tstep_mass_thresh_kgm-2: null     # default value: 1 kg/m^2
    normal_tstep_min: null                  # default value: 60 min
    medium_tstep_min: null                  # default value: 15 min
    small_tstep_min: null                   # default value: 1 min